### ISSUE TITLE
Insert into table don't work

### ISSUE THREAD

**Issue by divid3d** [nakagami/micropg#1]
Im trying to insert some data into table with:
cur.execute('INSERT INTO test (serial, lat, long) VALUES ({}, {}, {});'.format(1,lat,long))

but seems nothing happens. Does this library support INSERT operations?

**Comment by nakagami** [comment]
'serial' and 'long' are  data type.
Please show me CREATE TABLE statement.

**Comment by nakagami** [comment]
Version 0.2.2 has released. 

Fix error messages, and  simple test script is added

https://github.com/nakagami/micropg/blob/master/test_micropg.py
Check it

**Comment by nakagami** [comment]
Are you execute connection.commit() after insert statement ?
Probabry you need
```
connection.commit()
```
after
```
cur.execute("insert into...")
```

**Comment by divid3d** [comment]
Thank you. Everything works fine. I didn't use `conn.commit()` after `cur.execute()`.
