### ISSUE TITLE
TypeError: can't convert str to int

### ISSUE THREAD

**Issue by KhPhilip** [nakagami/micropg#3]
Hello, 
please help,
Standart example:
use scram-sha-256 \ md5\ trust - 
```
34: conn = micropg.connect (host=Nhost, port=Nport, user=Nuser, password=Npassword, database=Ndatabase)
35: cur = conn.cursor()
36: cur.execute('SELECT "ID_row", btn_id, btn_name FROM public."Buttons_ID";')
37: for r in cur.fetchall():
38: print(r[0], r[1])
39: conn.close()
```

Traceback (most recent call last):
  File "<stdin>", line 34, in <module>
  File "/lib/micropg.py", line 786, in connect
  File "/lib/micropg.py", line 385, in __init__
  File "/lib/micropg.py", line 680, in _open
TypeError: can't convert str to int

**Comment by nakagami** [comment]
It seems to be an error in the _open() method where it is converting from strings to numbers.
Do you know specifically which line and what kind of string you are trying to convert to a number?

Specifying an IP address like `192.168.0.10` as the hostname may help.

**Comment by KhPhilip** [comment]
_Specifying an IP address like 192.168.0.10 as the hostname may help._
Yes, I use a similar spelling (I just removed the exact data because I connect to an open address)

_It seems to be an error in the _open() method where it is converting from strings to numbers.
Do you know specifically which line and what kind of string you are trying to convert to a number?_

Here is the place where the error is triggered
 ```
 def _open(self):
        self.sock = socket.socket()
        self.sock.connect(socket.getaddrinfo(self.host, self.port)[0][-1])
```

just in case, I use RPI Pico W, it is relatively new

**Comment by nakagami** [comment]
How about this kind of modification?
```
diff --git a/micropg.py b/micropg.py
index 28af954..c9de3e6 100644
--- a/micropg.py
+++ b/micropg.py
@@ -678,7 +678,7 @@ class Connection(object):

     def _open(self):
         self.sock = socket.socket()
-        self.sock.connect(socket.getaddrinfo(self.host, self.port)[0][-1])
+        self.sock.connect((self.host, self.port))

         if self.timeout is not None:
             self.sock.settimeout(float(self.timeout))
```

or

```
diff --git a/micropg.py b/micropg.py
index 28af954..701341b 100644
--- a/micropg.py
+++ b/micropg.py
@@ -677,8 +677,8 @@ class Connection(object):
                 n += self.sock.send(b[n:])

     def _open(self):
-        self.sock = socket.socket()
-        self.sock.connect(socket.getaddrinfo(self.host, self.port)[0][-1])
+        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
+        self.sock.connect((self.host, self.port))

         if self.timeout is not None:
             self.sock.settimeout(float(self.timeout))
```

**Comment by KhPhilip** [comment]
Sorry, but it did not help, the error is the same, no change

**Comment by nakagami** [comment]
Hmmm, I don't know.
The only other thing I can think of is that port has a non-numeric value in it.

**Comment by KhPhilip** [comment]
It works it works ))))))

def _open(self):
        self.sock = socket.socket()
        self.sock.connect((self.host, self.port))

port number without quotation marks
conn = micropg.connect (host='127.0.0.1', **port=5432**, .....

Your different examples and Issues use quotation marks, and I am a "young" programmer, I am slow to find childish mistakes )
Thank you so much!
